# Generated by Django 5.2.5 on 2025-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='students', to='users.course'),
        ),
    ]
