# Generated by Django 5.2.5 on 2025-09-12 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text='A descrição da ação.', max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('is_read', models.BooleanField(default=False, help_text='Indica se a notificação foi visualizada.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='A data e hora em que a notificação foi criada.')),
                ('actor', models.ForeignKey(help_text='O usuário que realizou a ação.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='O usuário que recebe a notificação.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
